version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - currentVersion=$(cat version | sed 's/-SNAPSHOT//' | tr -d ' ')
      - echo $currentVersion
      - ./gradlew test
  post_build:
    commands:
      - echo Build completed on `date`
      - java -version
      - pwd
      - ls
      - ./gradlew build
artifacts:
  files:
    - '**/*'