version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - gradle test
  post_build:
    commands:
      - echo Build completed on `date`
      - java -version
      - pwd
      - ls
      - grade build -x test
artifacts:
  files:
    - '**/*'